site_name: Home Lab Dokument√°ci√≥
site_description: A Home Lab h√°l√≥zat, hardver √©s szoftver le√≠r√°sa, r√©szletes √©s val√≥s idej≈± dokument√°ci√≥val.
site_url: https://github.com/CreativeZoller/homeLabDocumenting

theme:
  name: material
  language: hu
  features:
    - navigation.tabs           # Fels≈ë f√ºlek a navig√°ci√≥hoz
    - navigation.sections       # Fels≈ë navig√°ci√≥ szekci√≥kra bontva
    - navigation.expand         # Automatkus leny√≠l√≥ almen√ºk
    - navigation.indexes        # 'index.md' f√°jlok haszn√°lata mapp√°k f≈ëoldalak√©nt
    - navigation.footer         # El≈ëz≈ë/K√∂vetkez≈ë linkek az oldal alj√°n
    - search.suggest            # Keres√©si javaslatok
    - search.highlight          # Tal√°latok kiemel√©se
    - content.code.annotate     # K√≥dr√©szletek annot√°l√°sa
    - navigation.top            # Oldals√≥ navig√°ci√≥ elrejt√©se, fels≈ë men√º
    - toc.follow                # Jobb oldali tartalomjegyz√©k k√∂veti a g√∂rget√©st
  
  # Sz√≠npaletta (k√∂nny≈± v√°lt√°s vil√°gos/s√∂t√©t m√≥d k√∂z√∂tt)
  palette:
    - scheme: default
      toggle:
        icon: material/weather-night
        name: V√°lt√°s s√∂t√©t m√≥dra
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: V√°lt√°s vil√°gos m√≥dra

# --- MARKDOWN B≈êV√çTM√âNYEK ---
markdown_extensions:
  - toc:
      permalink: true           # Fejl√©c link ikon a k√∂nny≈± hivatkoz√°shoz
  - attr_list
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
#  - pymdownx.mermaid
  - admonition
  - pymdownx.snippets
  - pymdownx.tasklist:
      custom_checkbox: true

# --- NAVIG√ÅCI√ì (A TARTALOMJEGYZ√âK) ---
nav:
  - üè† Kezd≈ëlap: index.md
  - √Åttekint√©s:
    - Home Lab fogalma √©s c√©lja: overview/index-overview.md
    - Home Lab el≈ënyei √©s kih√≠v√°sai: overview/benefits-challenges.md
  - Tervez√©s:
    - C√©lok √©s k√∂vetelm√©nyek: planning/goals-requirements.md
    - H√°l√≥zati tervez√©s: planning/network-design.md
    - Hardver kiv√°laszt√°s: planning/hardware-selection.md
    - Szoftver √©s szolg√°ltat√°sok: planning/software-services.md
  - H√°l√≥zati Topol√≥gia: 
    - √Åttekint√©s: network/overview.md
    - Fizikai Diagram: network/physical-diagram.md
  - H√°l√≥zat telep√≠t√©se:
    - Eszk√∂z√∂k megfelel≈ë k√∂t√©se: network-setup/device-connections.md
  - Eszk√∂z√∂k telep√≠t√©se:
    - Router: device-setup/router.md    
    - Switch: device-setup/switch.md
    - Raspberry Pi: device-setup/raspberry-pi.md
    - Home Server: device-setup/home-server.md
    - NAS: device-setup/nas.md
    